import = ["/home/dima/scripts/dotfiles/alacritty/one_dark.toml"]
live_config_reload = true

[font]
size = 12.0

[font.bold]
family = "JetBrains Mono"
style = "Bold"

#[font.italics]
#family = "JetBrains Mono"
#style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[[keyboard.bindings]]
chars = "\u0011"
key = "Q"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "B"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BF"
key = "F"
mods = "Alt|Shift"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"
mods = "None"

[shell]
program = "zsh"

[window]
dynamic_title = true
startup_mode = "Maximized"
