" Generated by vim-plug
" Mon 22 Nov 2021 07:12:39 PM IST
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['Dockerfile.vim'].commit = '2a31e6bcea5977209c05c728c4253d82fd873c82'
silent! let g:plugs['YouCompleteMe'].commit = '16ff59a048b822a49905fce24560de6fc7ac5b10'
silent! let g:plugs['auto-pairs'].commit = '39f06b873a8449af8ff6a3eee716d3da14d63a76'
silent! let g:plugs['bufexplorer'].commit = '99557c451ff6ed3bbb9b9f6215ad57e919740635'
silent! let g:plugs['fzf.vim'].commit = 'd6aa21476b2854694e6aa7b0941b8992a906c5ec'
silent! let g:plugs['indentLine'].commit = '5617a1cf7d315e6e6f84d825c85e3b669d220bfa'
silent! let g:plugs['linediff.vim'].commit = 'c7710dbc59881b038ca064b6c54fe482303e8304'
silent! let g:plugs['markdown-preview.nvim'].commit = 'e5bfe9b89dc9c2fbd24ed0f0596c85fd0568b143'
silent! let g:plugs['neovim-gui-shim'].commit = '668188542345e682addfc816af38b7073d376a64'
silent! let g:plugs['nerdcommenter'].commit = 'a65465d321f2f8a74b2ffa540b9b87563f7e12e8'
silent! let g:plugs['nerdtree'].commit = 'eed488b1cd1867bd25f19f90e10440c5cc7d6424'
silent! let g:plugs['nerdtree-git-plugin'].commit = 'e1fe727127a813095854a5b063c15e955a77eafb'
silent! let g:plugs['syntastic'].commit = '2c4b33f6e6679fb5f3824d9cd38d4813c71a19a3'
silent! let g:plugs['ultisnips'].commit = '53e1921e3ef015ef658e540c0aa9c4835f9c18a6'
silent! let g:plugs['vim-airline'].commit = '4b96f58902a34abda87fd3105e9d47a08801a891'
silent! let g:plugs['vim-airline-themes'].commit = '97cf3e6e638f936187d5f6e9b5eb1bdf0a4df256'
silent! let g:plugs['vim-better-whitespace'].commit = 'c5afbe91d29c5e3be81d5125ddcdc276fd1f1322'
silent! let g:plugs['vim-bufonly'].commit = '05a9f2d79f7aa7e2a94f9a6e29555e878e88d411'
silent! let g:plugs['vim-clang-format'].commit = '261d02c305f3ed361c39e3b9ca5d66b5b45df4c7'
silent! let g:plugs['vim-copypath'].commit = '7eec9f3fc40f11dec6eeaf9bc148ca06fcbcf125'
silent! let g:plugs['vim-cpp-enhanced-highlight'].commit = '4b7314a497ea2dd0a6911ccb94ce83b2d8684617'
silent! let g:plugs['vim-devicons'].commit = 'd16475cbd7d50664e3d9261951cd4415967c5c41'
silent! let g:plugs['vim-easy-align'].commit = '12dd6316974f71ce333e360c0260b4e1f81169c3'
silent! let g:plugs['vim-fugitive'].commit = '2e4ee0b5d6e61c6b3bc48e844343f89615dfc6e0'
silent! let g:plugs['vim-gitgutter'].commit = '256702dd1432894b3607d3de6cd660863b331818'
silent! let g:plugs['vim-monokai'].commit = '66f7dc9c63296ea6ba408faa60bebe54a34c57f2'
silent! let g:plugs['vim-nerdtree-syntax-highlight'].commit = '5178ee4d7f4e7761187df30bb709f703d91df18a'
silent! let g:plugs['vim-snippets'].commit = '43ed873ba09ac2d71992e773c68c75c6b85686c7'
silent! let g:plugs['vim-toml'].commit = '3c5face8e8944a217af45bc5bb708ff7dfcf1a54'

PlugUpdate!

