" Generated by vim-plug
" Sat 13 Nov 2021 02:51:37 AM IST
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['Dockerfile.vim'].commit = '86d744c6e4731d0014ef469f019a305e2d7baac0'
silent! let g:plugs['YouCompleteMe'].commit = '518275b599ab6dd7844c24022f6aec505fb4b07c'
silent! let g:plugs['auto-pairs'].commit = '39f06b873a8449af8ff6a3eee716d3da14d63a76'
silent! let g:plugs['bufexplorer'].commit = '99557c451ff6ed3bbb9b9f6215ad57e919740635'
silent! let g:plugs['fzf.vim'].commit = 'b1afeca8cc02030f450bf1feee015d40988f86e3'
silent! let g:plugs['indentLine'].commit = '5617a1cf7d315e6e6f84d825c85e3b669d220bfa'
silent! let g:plugs['linediff.vim'].commit = 'c7710dbc59881b038ca064b6c54fe482303e8304'
silent! let g:plugs['markdown-preview.nvim'].commit = 'e5bfe9b89dc9c2fbd24ed0f0596c85fd0568b143'
silent! let g:plugs['neovim-gui-shim'].commit = '668188542345e682addfc816af38b7073d376a64'
silent! let g:plugs['nerdcommenter'].commit = '2c87cae76ed88f3b0c957df68c03573ecafa3728'
silent! let g:plugs['nerdtree'].commit = '0e71462f90fb4bd09121eeba829512cc24ab5c97'
silent! let g:plugs['nerdtree-git-plugin'].commit = 'e1fe727127a813095854a5b063c15e955a77eafb'
silent! let g:plugs['syntastic'].commit = '7414f30365a342e1d89072d474a35913643b6eec'
silent! let g:plugs['ultisnips'].commit = '8803960a4e09daf1ad4d82e16a25bbdb4c78530e'
silent! let g:plugs['vim-airline'].commit = '0de4c9df21abf9256091d205148601f718d3a12c'
silent! let g:plugs['vim-airline-themes'].commit = '97cf3e6e638f936187d5f6e9b5eb1bdf0a4df256'
silent! let g:plugs['vim-better-whitespace'].commit = '8cf4b2175dd61416c2fe7d3234324a6c59d678de'
silent! let g:plugs['vim-bufonly'].commit = '05a9f2d79f7aa7e2a94f9a6e29555e878e88d411'
silent! let g:plugs['vim-clang-format'].commit = '95593b67723f23979cd7344ecfd049f2f917830f'
silent! let g:plugs['vim-copypath'].commit = '7eec9f3fc40f11dec6eeaf9bc148ca06fcbcf125'
silent! let g:plugs['vim-cpp-enhanced-highlight'].commit = '4b7314a497ea2dd0a6911ccb94ce83b2d8684617'
silent! let g:plugs['vim-easy-align'].commit = '12dd6316974f71ce333e360c0260b4e1f81169c3'
silent! let g:plugs['vim-fugitive'].commit = 'e7d2e876900c4e09be59d4e1037ecceeeb880987'
silent! let g:plugs['vim-gitgutter'].commit = '549fb96d5890d5225afda070ca041468c2c770e5'
silent! let g:plugs['vim-monokai'].commit = '66f7dc9c63296ea6ba408faa60bebe54a34c57f2'
silent! let g:plugs['vim-snippets'].commit = '9e5219ae92f9b1b2ee23aff067618a6008a74fa5'
silent! let g:plugs['vim-toml'].commit = '3c5face8e8944a217af45bc5bb708ff7dfcf1a54'

PlugUpdate!

